version: '3'
#docker-compose -f ./docker-compose.yml up or docker-compose up
name: python-cicd-restapi
services:
  
  fn-cicd-basic-omni_es:
    image: fn-cicd-basic-api:omni_es
    container_name: fn-cicd-basic-api-omni_es
    build:
      context: .
      dockerfile: Dockerfile
      target: omni_es
    ports:
      - 9203:9201
    # restart: unless-stopped
    environment:
      # v_7
      # - node.name=fn-dm-bees-omni-data-01
      # - discovery.type=single-node
      # - http.port=9201
      # - http.cors.enabled=true
      # - http.cors.allow-origin=* 
      # - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      # - http.cors.allow-credentials=true
      # - xpack.security.enabled=false
      # - bootstrap.system_call_filter=false
      # - ES_JAVA_OPTS=-Xms1g -Xmx1g
      
      # v_8
      - node.name=fn-dm-bees-omni-data-01
      - cluster.name=docker-elasticsearch
      - cluster.initial_master_nodes=fn-dm-bees-omni-data-01
      - discovery.seed_hosts=fn-dm-bees-omni-data-01
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=basic
      - action.destructive_requires_name=false
      - http.port=9201
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - bridge
      
  fn-cicd-basic-api:
    image: fn-cicd-basic-api:es
    container_name: fn-cicd-basic-api
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - 15555:5555
    volumes:
      # - ${PROJECTS_DIR}/python-CICD-fastapi-basic:/app/FN-BEES-Services
      - ./:/app/FN-Basic-Services
    restart: unless-stopped
    environment:
      - ES_HOST=http://host.docker.internal:9203
    networks:
      - bridge
      
  fn-cicd-basic-api-test:
    image: fn-cicd-basic-api:test
    container_name: fn-cicd-basic-api-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    ports:
      - 15556:5555
    volumes:
      - ./:/app/FN-Basic-Services
    # restart: unless-stopped
    environment:
      - ES_HOST=http://host.docker.internal:9203
    networks:
      - bridge
      
volumes:
  data:
    driver: local
    
networks:
  bridge:
    driver: bridge