name: 'Elasticsearch Action with Plugins'
description: 'Elasticsearch Action with Plugins, analysis-icu and analysis-kuromoji.'
author: 'Motoyasu Yamada'
branding:
  icon: 'database'
  color: 'green'
inputs:
  stack-version:
    description: 'The version of Elasticsearch'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STACK_VERSION: ${{ inputs.stack-version }}